Stage2
AnastasiaKivachuk/Webix_Jet_Test_Application pull request #2
Opened 2019-07-02 20:56 UTC by AnastasiaKivachuk

2019-07-04 20:21 UTC, HelgaListopad requested changes

2019-07-04 20:21 UTC, HelgaListopad commented on sources/models/contacts.js
> +			obj.newBirthday = obj.newBirthday || strForatting(obj.Birthday);
Что нужно помнить: `strForatting` ожидает строку определённого формата.
Поэтому, если obj.Birthday или obj.StartDate в пришедших данных нет, то, что такие парсеры вернут пустую строку, можно считать счастливым совпедением, а наличие этих полей (if obj.Birthday) имеет смысл проверять.

2019-07-04 20:21 UTC, HelgaListopad commented on sources/views/contactform.js
> +												this.$$("preview").show();
Лишний метод

2019-07-04 20:21 UTC, HelgaListopad commented on sources/views/contactform.js
> +										this.$$("preview").show();
Лишний метод

2019-07-04 20:21 UTC, HelgaListopad commented on sources/views/contactform.js
> +								this.getRoot().getParentView().queryView("list").enable();
`getParentView` между классами (как и между виджетами в разных классах) лучше использовать в последнюю очередь, если других вариантов нет. 
Здесь он есть - ты вызываешь `showContactInfoView`, чтобы правильно переключить вьюшки. Там же можно проверить на [list.isEnabled()](https://docs.webix.com/api__link__ui.list_isenabled.html) и включить его, если нужно.

2019-07-04 20:21 UTC, HelgaListopad commented on sources/views/contactform.js
> +										this.getRoot().getParentView().queryView("list").enable();
`getParentView` между классами (как и между виджетами в разных классах) лучше использовать в последнюю очередь, если других вариантов нет. 
Здесь он есть - ты вызываешь `showContactInfoView`, чтобы правильно переключить вьюшки. Там же можно проверить на [list.isEnabled()](https://docs.webix.com/api__link__ui.list_isenabled.html) и включить его, если нужно.

2019-07-04 20:21 UTC, HelgaListopad commented on sources/views/contactform.js
> +										let lastId = this.getRoot().getParentView().queryView("list").getLastId();
`.getLastId()` в данном случае вернёт "промежуточное" ID, присвоенное новому контакту до того, как пришёл ответ с сервера.
Я рассказывала, что после того, как наш сервер сохраняет новую запись (сохранение - асинхронная, но быстрая операция), поле `id` обновляется.
Вся работа с контактом должна быть основана именно на новом значении.

Что сейчас плохо:
При добавлении контакта ты получаешь url вида `/top/contacts?id=1562258408215/` до того, как с сервера пришёл ответ.
После ответа с сервера контакта с таким ID уже не существует в коллекции, поэтому если добавить для него activities или files, они не будут связаны с реально добавленным контактом.
Кроме того, попытка удалить контакт с таким ID вызовет ошибку.

Что сделать: вызвать `setParam` позже c нормальным значением.
Отловить нужный момент и новое ID можно через 
- [waitSave](https://docs.webix.com/api__link__datacollection_waitsave.html) промис
- событие [onIdChange](https://docs.webix.com/api__datastore_onidchange_event.html) у DataStore коллекции Contacts 
- через другие события [DataProcessor](https://docs.webix.com/desktop__dataprocessor.html)'а коллекции

2019-07-04 20:21 UTC, HelgaListopad commented on sources/views/contactform.js
> +					this.$$("myform").setValues({});
Если цель - очистить форму, то `clear` и `clearValidation`, и лучше это делать в любом случае, то есть вынести выше из блока if.

2019-07-04 20:21 UTC, HelgaListopad commented on sources/views/contactform.js
> +					this.getRoot().getParentView().queryView("list").disable();
`getParentView` между классами (как и между виджетами в разных классах) лучше использовать в последнюю очередь, если других вариантов нет.
Отключить лист можно ещё на этапе `showContactForm` подобной логикой
```
this.on(this.app, "showContactForm", (mode) => {
   this.show(form_url).then(()=>{ mode == add ? list.disable() : return; })
```

2019-07-04 20:21 UTC, HelgaListopad commented on sources/views/contactform.js
> +				if (mode === "Edit") {
Строчки 
```
this.$$("SaveAddBTN").setValue();
this.$$("preview").setValues();
```
Встречаются в двух блоках - можно вынести наверх

2019-07-04 20:21 UTC, HelgaListopad commented on sources/views/contactform.js
> +						this.$$("myform").clearValidation();
Как и написано выше - перенести над блоком if-else

2019-07-04 20:21 UTC, HelgaListopad commented on sources/views/contactinfo.js
> +											this.getRoot().getParentView().queryView("list").select(firstId);
Ещё один `getParentView`.
Весь этот процесс (удаление контакта + удаление связанных записей) можно перенести в отдельный метод/событие.
Кроме того, 
- `firstId` коллекции и листа могут не совпадать (в теории, лист, можно отсортировать), 
- если удалить последнюю запись из коллекции, этот метод вернёт undefined. 

Если вместо селекта вызвать 
```
Contacts.remove(id);
this.show("/top/contacts/contactinfo")
```
urlChange сам восстановит параметр с селектом.
`show` (точнее, эти две строчки) лучше вызывать последним шагом.

2019-07-04 20:21 UTC, HelgaListopad commented on sources/views/contacts.js
> +						this.show("contactform").then();
Ниже есть метод `showContactForm`

2019-07-04 20:21 UTC, HelgaListopad commented on sources/views/contacts.js
> +		});
Почему бы не вызвать просто
```
this.on(this.app, "showContactInfoView", (id) => {
	this.show("contactinfo");
});
```
Если обрабатывать remove отдельно (описано выше), в этом методе останется только перейти от form к info уже существующего контакта, а это можно сделать, не меняя параметр

2019-07-04 20:21 UTC, HelgaListopad commented on sources/views/contacts.js
> +			});
Параметр mode не обязательно должен висеть на parent-классе формы (раз нужен он только в форме)
Проще было бы
```
this.on(this.app, "showContactForm", (mode) => {
	this.show(`contactform?mode=${mode}`);
});
```

2019-07-05 09:31 UTC, AnastasiaKivachuk commented on sources/models/contacts.js
> +			obj.newBirthday = obj.newBirthday || strForatting(obj.Birthday);
if (obj.StartDate.toString() !== "") {
				obj.newStartDate = obj.newStartDate || strForatting(obj.StartDate);
			}
			if (obj.Birthday.toString() !== "") {
				obj.newBirthday = obj.newBirthday || strForatting(obj.Birthday);
			}

2019-07-05 09:31 UTC, AnastasiaKivachuk commented on sources/views/contactform.js
> +												this.$$("preview").show();
Убрала строку this.$$("preview").show();

2019-07-05 09:32 UTC, AnastasiaKivachuk commented on sources/views/contactform.js
> +										this.$$("preview").show();
Убрала строку this.$$("preview").show();

2019-07-05 09:45 UTC, AnastasiaKivachuk commented on sources/views/contacts.js
> +			});
исправила)

2019-07-05 09:52 UTC, AnastasiaKivachuk commented on sources/views/contacts.js
> +		});
исправила

2019-07-05 09:53 UTC, AnastasiaKivachuk commented on sources/views/contacts.js
> +						this.show("contactform").then();
this.show(`contactform?mode=${"Add"}`);
так???

2019-07-05 09:57 UTC, AnastasiaKivachuk commented on sources/views/contactinfo.js
> +											this.getRoot().getParentView().queryView("list").select(firstId);
убрала лишнее

2019-07-05 10:09 UTC, AnastasiaKivachuk commented on sources/views/contactform.js
> +								this.getRoot().getParentView().queryView("list").enable();
Добавила проверку в showContactInfoView
if (!this.$$("contactList").isEnabled()) {
				this.$$("contactList").enable();
			}

2019-07-05 10:11 UTC, AnastasiaKivachuk commented on sources/views/contactform.js
> +										this.getRoot().getParentView().queryView("list").enable();
исправила

2019-07-05 10:26 UTC, AnastasiaKivachuk commented on sources/views/contactform.js
> +					this.$$("myform").setValues({});
исправила на
this.$$("myform").clear();
this.$$("myform").clearValidation();

2019-07-05 11:09 UTC, AnastasiaKivachuk commented on sources/views/contactform.js
> +						this.$$("myform").clearValidation();
исправила

2019-07-05 12:16 UTC, AnastasiaKivachuk commented on sources/views/contactform.js
> +				if (mode === "Edit") {
исправила

2019-07-05 13:03 UTC, AnastasiaKivachuk commented on sources/views/contactform.js
> +										let lastId = this.getRoot().getParentView().queryView("list").getLastId();
сделано

2019-07-05 13:04 UTC, AnastasiaKivachuk commented on sources/views/contactform.js
> +					this.getRoot().getParentView().queryView("list").disable();
исправлено

2019-07-06 20:30 UTC, HelgaListopad approved these changes

2019-07-06 20:30 UTC, merged