Stage3
AnastasiaKivachuk/Webix_Jet_Test_Application pull request #3
Opened 2019-07-07 07:18 UTC by AnastasiaKivachuk

2019-07-08 12:13 UTC, HelgaListopad requested changes

2019-07-08 12:13 UTC, HelgaListopad commented on sources/models/ActivityType.js
> +		},
$init + $update можно смело менять на один $change

2019-07-08 12:13 UTC, HelgaListopad commented on sources/myapp.js
> +		//  storage: webix.locale.storage);
Неиспользуемый/ненужный код лучше убирать

2019-07-08 12:13 UTC, HelgaListopad commented on sources/views/commonTable.js
> +							editor: "text"
Логически, если иконка есть, она должна где-то использоваться - в данном случае, как минимум в [template](https://docs.webix.com/desktop__icon_types.html#webixiconcssclass) этой конкретной колонки. В идеале - везде рядом с названием actviity type.
И editor для неё не подойдёт - иконку отрисовать "на удачу" из произвольного текста редко получается.
Для этого нужно сделать выборку названий из используемого шрифта (materialdesignicons, 6-10 будет более чем достаточно) и использовать как column collection для выбора нужного значения.

2019-07-08 12:13 UTC, HelgaListopad commented on sources/views/settings.js
> +					template: "Activity type",
На мой взгляд, не хватает локализации

2019-07-08 12:13 UTC, HelgaListopad commented on sources/views/settings.js
> +					template: "Statuses",
Локализация

2019-07-08 12:13 UTC, HelgaListopad commented on sources/views/settings.js
> +		console.log(value);
Логи тоже лучше удалять

2019-07-08 12:13 UTC, HelgaListopad commented on sources/views/activities.js
> +					let lastDayOfWeek = new Date(new Date().getTime() + 24 * 60 * 60 *
`compare` вызывается для каждого айтема при фильтрации - соответственно, ворох переменных объявляется множество раз.
Лучше вынести отсюда все переменные, не зависящие от item (только от new Date) и объявлять их один раз на init класса.
Для красоты я предложила бы вынести их в функцию вообще за пределы класса ActivityView
```
function getDates(){
	let d = new Date();
	let dates = {};
	dates.currentYear = d.getFullYear();
	/* и так далее */
	return dates
};
```
Потом на init получить их перед вызовом registerFilter и использовать там

2019-07-08 12:13 UTC, HelgaListopad commented on sources/views/commonTable.js
> +					scroll: "auto",
scroll:"auto" - невалидное значение
Поддерживаются только true, "x", "y", "xy"

2019-07-08 12:22 UTC, AnastasiaKivachuk commented on sources/myapp.js
> +		//  storage: webix.locale.storage);
убрала

2019-07-08 12:24 UTC, AnastasiaKivachuk commented on sources/views/settings.js
> +					template: "Activity type",
исправила

2019-07-08 12:24 UTC, AnastasiaKivachuk commented on sources/views/settings.js
> +					template: "Statuses",
исправила

2019-07-08 12:33 UTC, AnastasiaKivachuk commented on sources/views/settings.js
> +		console.log(value);
убрала

2019-07-08 12:41 UTC, AnastasiaKivachuk commented on sources/views/commonTable.js
> +					scroll: "auto",
исправила

2019-07-08 12:44 UTC, AnastasiaKivachuk commented on sources/models/ActivityType.js
> +		},
исправила

2019-07-08 13:44 UTC, AnastasiaKivachuk commented on sources/views/activities.js
> +					let lastDayOfWeek = new Date(new Date().getTime() + 24 * 60 * 60 *
исправила

2019-07-09 07:35 UTC, Zwillinge commented on sources/models/ActivityType.js
> +		},
а зачем там `obj.value = obj.Value;` повторяется два раза?

2019-07-09 07:36 UTC, AnastasiaKivachuk commented on sources/views/commonTable.js
> +							editor: "text"
исправила

2019-07-09 07:37 UTC, AnastasiaKivachuk commented on sources/models/ActivityType.js
> +		},
не заметила)
убрала

2019-07-09 07:50 UTC, Zwillinge commented on sources/views/activities.js
> +					let lastDayOfWeek = new Date(new Date().getTime() + 24 * 60 * 60 *
фильтры today и позже не должны возвращать closed активити - никому не интересно видеть закрытые таски в пуле задач на будущее)

2019-07-09 07:57 UTC, AnastasiaKivachuk commented on sources/views/activities.js
> +					let lastDayOfWeek = new Date(new Date().getTime() + 24 * 60 * 60 *
исправила

2019-07-09 07:59 UTC, Zwillinge requested changes

2019-07-09 07:59 UTC, Zwillinge commented on sources/views/activities.js
> +						const item = config.collection.data.find(ind => parseInt(ind.id) === parseInt(value));
зачем так сложно, если можно пользоваться стандартным getItem?
~~~
config.collection.getItem(value);
~~~

2019-07-09 07:59 UTC, Zwillinge commented on sources/views/commonTable.js
> +						this._tdata.remove(idS);
если ни один элемент не выбран - кидает ошибку

2019-07-09 07:59 UTC, Zwillinge commented on sources/views/commonTable.js
> +						this._tdata.remove(idS);
и confirm-а нет

2019-07-09 07:59 UTC, Zwillinge commented on sources/views/tabbaractivityfiles.js
> +									const item = config.collection.data.find(ind => parseInt(ind.id)
getItem проще

2019-07-09 08:19 UTC, AnastasiaKivachuk commented on sources/views/commonTable.js
> +						this._tdata.remove(idS);
исправила

2019-07-09 08:37 UTC, AnastasiaKivachuk commented on sources/views/activities.js
> +						const item = config.collection.data.find(ind => parseInt(ind.id) === parseInt(value));
исправила

2019-07-09 08:39 UTC, AnastasiaKivachuk commented on sources/views/tabbaractivityfiles.js
> +									const item = config.collection.data.find(ind => parseInt(ind.id)
исправила

2019-07-09 10:01 UTC, Zwillinge requested changes

2019-07-09 10:01 UTC, Zwillinge commented on sources/views/commonTable.js
> +					this._tdata.add({
при добавлении нескольких записей последовательно - новые становятся не видны (под скроллом).
простейшее решение - добавлять в нулевую позицию `data.add(obj, 0)`

2019-07-09 10:01 UTC, Zwillinge commented on sources/views/commonTable.js
> +					this._tdata.add({
и еще по юзабилити -  если в таблице нужен селекшен, то лучше редактирование повесить на dblclick, чтобы разделить эти действия

2019-07-09 12:31 UTC, merged